### ISSUE TITLE
Too much warnings

### ISSUE THREAD

**Issue by omid3098** [sigtrapgames/SmartData#11] opened 2019-02-08 15:05 UTC
When I clone this repository together with Rely, I will get over 50 warnings without changing anything, and as I try to have 0 warnings in my projects, I can not skip warnings related to this repositories.

Would you please consider a time to remove these warnings?

![image](https://user-images.githubusercontent.com/6388730/52486331-18285880-2bd0-11e9-8de3-f3dfed89d67a.png)

**Comment by SixWays** [comment] 2019-02-09 13:46
Unfortunately this is a symptom of the fact that Unity (or possibly .Net 4.x) no longer supresses this warning for non-public fields with the `[SerializeField]` attribute. This is [logged as a bug here](https://issuetracker.unity3d.com/issues/serializedfield-fields-produce-field-is-never-assigned-to-dot-dot-dot-warning), and although Unity have closed it as "by design" (which is utterly absurd), it seems to still be under consideration. I'm loathe to either a) litter my code with #pragmas or b) make all my fields public to fix an issue which really belongs to Unity, as this affects all code currently.

**Comment by omid3098** [comment] 2019-02-09 17:11
Ok, thanks for information. So there is nothing to do in this repository!
I personally do a null check and set a default value to hide these kinds of warnigns.
```
[SerializeField] Collider collider;
void Awake(){
   if (collider == null) collider = GetComponent<Collider>();
   // or using find object in some cases.
   // the line may not actually execute, but the warning will be gone.
}
```

**Closed** 2019-02-20 15:09 UTC
