### ISSUE TITLE
Updated from v0.1.0 to the latest in the repo for the latest fixes and have this error in my console

### ISSUE THREAD

**Issue by yaustar** [sigtrapgames/SmartData#10] opened 2019-01-18 14:45 UTC
```
NullReferenceException: Object reference not set to an instance of an object
SmartData.Components.SmartRefUnbinder.OnEditorChangePlayMode (PlayModeStateChange change) (at Assets/SmartData/Utilities/SmartRefUnbinder.cs:40)
UnityEditor.EditorApplication.Internal_PlayModeStateChanged (PlayModeStateChange state) (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:282)
```

All the auto listen events seem to be disabled on the readers as an end result.

Thanks in advance!

**Comment by sigtrapgames** [comment] 2019-01-21 18:49
This is a duplicate of #9 - apologies for not having sorted that yet.

**Closed by sigtrapgames** 2019-01-21 18:49 UTC
